name: Publish to GH Pages

on:
  push:
    branches: [ master ]

jobs:
  publish:

    runs-on: ubuntu-latest
    
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: true
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Run publish
      run: dotnet publish -c release -o .
    - name: ls
      run: ls
    #- name: Push to gh-pages
    #  run: git push -u origin gh-pages
