name: Publish to GH Pages

on:
  push:
    branches: [ master ]

jobs:
  publish:

    runs-on: ubuntu-latest
    
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: true
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Create temp directory
      run: mkdir $GITHUB_SHA
    - name: Move everything to temp directory
      run:  |
        # Enables extended pattern matching features to use pathname expansions
        shopt -s extglob
        mv !($GITHUB_SHA) $GITHUB_SHA
    - name: Run publish
      run: dotnet publish -c release -o . $GITHUB_SHA
    - uses: actions/checkout@v2
      with:
        ref: gh-pages
        path: gh-pages
    - name: Update gh-pages working directory
      run: rsync -a wwwroot/ gh-pages/
    - name: Prepare commit message
      run: |
        git log --format=%B -n 1 $GITHUB_SHA -- > commit_message.txt
        echo "Automatic commit by $GITHUB_WORKFLOW" >> commit_message.txt
    - name: Commit and push to gh-pages
      run: |
        cd gh-pages
        git config --global user.email "action@github.com"
        git config --global user.name "$GITHUB_WORKFLOW"
        git commit -F ../commit_message.txt -a
        git push
