name: Publish to GH Pages

on:
  push:
    branches: [ master ]

jobs:
  publish:

    runs-on: ubuntu-latest
    
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: true
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Create temp directory
      run: mkdir $GITHUB_SHA
    - name: Move everything to temp directory
      run:  |
        # Enables extended pattern matching features to use pathname expansions
        shopt -s extglob
        mv !($GITHUB_SHA) $GITHUB_SHA
    - name: Run publish
      run: dotnet publish -c release -o . $GITHUB_SHA
    - name: Remove temp directory
      run: rm -r $GITHUB_SHA
    #- name: Move wwwroot files into root directory
    #  run: mv wwwroot/* .
    #- name: Remove extra files
    #  run: rm -r web.config wwwroot
    - uses: actions/checkout@v2
      with:
        ref: gh-pages
        path: gh-pages
    - name: ls
      run: ls
    - name: git things
      run: |
        cd gh-pages
        rsync -a ../wwwroot/ ./
        git commit -m "Add changes" -a
        git push
